// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
)

type BlocksP struct {
	Idx      int64
	ID       string
	Bytes    []byte
	Decoded  int64
	TypeID   sql.NullInt64
	Height   sql.NullInt64
	Ts       sql.NullInt64
	ParentID sql.NullString
}

type TxsP struct {
	ID               string
	BlockID          string
	TypeID           int64
	UnsignedTx       string
	Memo             sql.NullString
	NodeID           sql.NullString
	ValidatorStartTs sql.NullInt64
	ValidatorEndTs   sql.NullInt64
	ValidatorWeight  sql.NullInt64
	SourceChain      sql.NullString
	DestinationChain sql.NullString
	OutputAddrs      sql.NullString
	StakeAddrs       sql.NullString
	RewardsAddrs     sql.NullString
}

type TypeID struct {
	ID   int64
	Name string
}
